[[redirects]]
  from = "/amadeus/*"
  to = "https://test.api.amadeus.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/weatherapi/*"
  to = "https://dataservice.accuweather.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}